trigger: none



jobs:
  - job: test
    displayName: Test job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - script: |
          echo Installing tofu...
          curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
          chmod +x install-opentofu.sh
          ./install-opentofu.sh --install-method deb
          rm install-opentofu.sh
        displayName: 'Install tofu'
      
      - task: TerraformDrift@1
        inputs:
          tool: 'terraform'
          workingDirectory: '$(System.DefaultWorkingDirectory)/tofu'
          provider: 'azure'
          azureSubscription: 'Azure subscription 1(836dac06-9190-4ca2-980f-c1fa69e59375)'