trigger: none

jobs:
  - job: test
    displayName: Test job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - script: |
          echo Installing tofu...
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://get.opentofu.org/opentofu.gpg | sudo tee /etc/apt/keyrings/opentofu.gpg >/dev/null
          curl -fsSL https://packages.opentofu.org/opentofu/tofu/gpgkey | sudo gpg --no-tty --batch --dearmor -o /etc/apt/keyrings/opentofu-repo.gpg >/dev/null
          sudo chmod a+r /etc/apt/keyrings/opentofu.gpg
          echo \
            "deb [signed-by=/etc/apt/keyrings/opentofu.gpg,/etc/apt/keyrings/opentofu-repo.gpg] https://packages.opentofu.org/opentofu/tofu/any/ any main
          deb-src [signed-by=/etc/apt/keyrings/opentofu.gpg,/etc/apt/keyrings/opentofu-repo.gpg] https://packages.opentofu.org/opentofu/tofu/any/ any main" | \
          sudo tee /etc/apt/sources.list.d/opentofu.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y tofu
        displayName: 'Install tofu'

      - script: |
          echo Verifying tofu...
          command -v tofu >/dev/null 2>&1 || { echo >&2 "Tofu is not installed or not available globally. Aborting."; exit 1; }
          echo 'export PATH=$PATH:/snap/bin' >> ~/.bashrc
          source ~/.bashrc
        displayName: 'Verify tofu'

      - script: |
          echo Determining tofu installation location...
          which tofu
        displayName: 'Determine tofu installation location'

      
      
      - task: TerraformDrift@1
        inputs:
          tool: 'tofu'
          workingDirectory: '$(System.DefaultWorkingDirectory)/tofu'
          provider: 'azure'
          azureSubscription: 'Azure subscription 1(836dac06-9190-4ca2-980f-c1fa69e59375)'