trigger: none



jobs:
  - job: test
    displayName: Test job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - script: |
          echo Installing tofu...
          sudo snap install --classic opentofu
        displayName: 'Install tofu'

      - script: |
          echo Verifying tofu...
          command -v tofu >/dev/null 2>&1 || { echo >&2 "Tofu is not installed or not available globally. Aborting."; exit 1; }
        displayName: 'Verify tofu'
      
      - task: TerraformDrift@1
        inputs:
          tool: 'tofu'
          workingDirectory: '$(System.DefaultWorkingDirectory)/tofu'
          provider: 'azure'
          azureSubscription: 'Azure subscription 1(836dac06-9190-4ca2-980f-c1fa69e59375)'