trigger: none

jobs:
  - job: test
    displayName: Test job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '26.0.0'
      - script: |
          sudo usermod -aG docker $USER
          docker info
        displayName: 'Add user to Docker group and check Docker config'
       
      - task: TerraformDrift@1
        inputs:
          tool: 'tofu'
          workingDirectory: 'tofu'
          provider: 'azure'
          azureSubscription: 'Azure subscription 1(836dac06-9190-4ca2-980f-c1fa69e59375)'
          autoReconcile: true