trigger: none

jobs:
  - job: test
    displayName: Test job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'
       
       
      - task: TerraformDrift@1
        inputs:
          tool: 'tofu'
          workingDirectory: 'tofu'
          provider: 'azure'
          azureSubscription: 'Azure subscription 1(836dac06-9190-4ca2-980f-c1fa69e59375)'