name: DockerImageCI-AWS
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: gcp-sdk/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/gcpopentofu:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/gcpopentofu:latest

